replicaCount: 1

image:
  repository: harbor.phink8s.com/library/mylivetemps
  pullPolicy: Always

namespace: web-app

secretsName: mylivetemps-secrets

service:
  service: mylivetemps
  port: 80

ingress:
  enabled: true
  className: traefik
  host: temps.phink8s.com
  secretName: wildcard-phink8s.com-tls