apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          envFrom:
            - secretRef:
                name: {{ .Values.secretsName }}
          volumeMounts:
            - name: {{ .Values.deployment.volumeMounts.name }}
              mountPath: {{ .Values.deployment.volumeMounts.mountPath }}
      volumes:
        - name: {{ .Values.deployment.volumeMounts.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistentVolumeClaim.name }}